apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nineinfra-business-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: nineinfra
      app: nineinfra-business-simulator
  template:
    metadata:
      labels:
        cluster: nineinfra
        app: nineinfra-business-simulator
    spec:
      containers:
      - name: simulator
        image: nineinfra/simulator:v0.8.0
        command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
        env:
        - name: MYSQL_PWD
          value: "nineinfra"
        volumeMounts:
        - name: log
          mountPath: /opt/nineinfra/logs
  volumeClaimTemplates:
  - metadata:
      name: log
    spec:
      storageClassName: nineinfra-default
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
